### ISSUE TITLE
Undo the "change colour of message background" by default

### ISSUE THREAD

**Issue by Vexthecollector** [ShoyuVanilla/FoundryVTT-Chat-Portrait#104]
Just updated and this was turned on by default. It made every message in chat unreadable.

Would be nice if this setting was turned off by default, because it can mess with some systems and make messages unreadable.

**Comment by esheyw** [comment]
As a workaround, you could force it off for everyone with [force client settings](https://gitlab.com/kimitsu_desu/force-client-settings) or [socket settings](https://github.com/BlitzKraig/fvtt-SocketSettings).

**Comment by p4535992** [comment]
A little to late, done on version 0.7.3
