### ISSUE TITLE
Compatibility with DF Chat Enhancements module

### ISSUE THREAD

**Issue by jbblily** [ShoyuVanilla/FoundryVTT-Chat-Portrait#105]
Hello. Thank you for maintaining this module.

However, there is an imcompatibility with DF Chat Enhancements module.

After the update, when I enable 'Chat merge' feature, Chat Portrait shows portrait into 'merged chat', which is quite annoying.

Former version didn't have this kind of problem. Can you fix this issue?

I appreciate your hard work.

**Comment by p4535992** [comment]
Should be fixed with 0.7.4
