### ISSUE TITLE
[BUG] DnD5e - Image Replacer for skill rolls choosing generic attribute icon instead of specific skill icon

### ISSUE THREAD

**Issue by tregolani** [ShoyuVanilla/FoundryVTT-Chat-Portrait#107]
**Module Version:** v0.7.4

**Describe the bug**
When rolling a skill check in the DnD5e system, the image replace feature chooses the generic attribute icons ("bear" for strength-based checks, "cat" for dex-based checks, etc) instead of the skill-specific icons. However, checks made before the module was installed and then were updated to use the Chat Portrait Styling do show the correct icons for the skills rolled.

**Screenshots**
Old Skill Rolls updated with Chat Portrait (from before it was installed): 
![Skill Rolls_032022](https://user-images.githubusercontent.com/64651202/172098674-acc092b2-13e2-4a55-81e9-6449455a681e.PNG)

New Skill Rolls after Chat Portrait has been installed: 
![Skill Rolls_06052022](https://user-images.githubusercontent.com/64651202/172098676-0c383efc-1f8e-4080-ad3f-f4a9ee76d7a2.PNG)

**Browser:**
 - Chrome 102.0.5005.63
 - Firefox 101.0

**Foundry Version:** 
v0.9.269

**Game System:** 
DnD5e - v1.6.1

**Additional context**
Tidy5e Sheet
MidiQOL

**Comment by p4535992** [comment]
Try out 0.8.0 ad tell me if the issue persist
