### ISSUE TITLE
[BUG] Damage dice results in Conan 2d20 are incorrectly visualized when Chat Portrait is enabled.

### ISSUE THREAD

**Issue by r-valyar** [ShoyuVanilla/FoundryVTT-Chat-Portrait#110]
**Module Version:** v0.7.4

**Describe the bug**
When Chat Portraits module is enabled for Conan 2d20 system, the damage dice report shows incorrect effect icons. Somehow the module tampers with the way dice result is visualized. The text-based report is correct though. 

**To Reproduce**
1. Create PC or NPC
2. Make damage roll with any weapon or ability
3. See error

**Expected behavior**
The dice icon should show the correct number of effects rolled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63558984/178922421-753933f3-0e75-4b7a-b89d-7d7183983175.png)![image](https://user-images.githubusercontent.com/63558984/178922451-17d2a68a-075c-4be6-87c4-65609c7a4b3a.png)

**Browser:**
 All

**Foundry Version:** 
v9.269

**Game System:** 
Conan 2d20

**Additional context**
I have created a bug report to Conan 2d20 system as well, as I am not sure in which field this bug falls to: https://gitlab.com/fvtt-modiphius/foundryvtt-conan2d20/-/issues/271

**Comment by p4535992** [comment]
It should be fixed, but reopen the ticket if the issue still persist
