### ISSUE TITLE
Toggle option to force settings on players

### ISSUE THREAD

**Issue by Nedrapter** [ShoyuVanilla/FoundryVTT-Chat-Portrait#111]
Hello!
I've been long time user of this module and it's part of my core Foundry experience. It does everything I need it to...except one thing, which used to be doing in older versions. At some point, some settings (if not all) became per user instead of global. That messed up my games. I use full art pictures on sheets and carefully displayed tokens on the canvas. That lets my player see the basic visual I want them to see, with surprise reveals later on, with the full character art (from the actor sheet).
Now the problem is that some players change it (or have it accidentally set) to viewing the actor image in chat instead of token image...Which as you can imagine ruins the above concept. I tried to tell people to change their setting but it didn't work. Some either get tempted and change it back, some settings get mixed, I have more than 60 players per week and it's a mess...

I would like a toggle to "force" some (if not all) settings on all users, or a global setting (as it was in earlier versions).

**Comment by p4535992** [comment]
For accomplsih that there are others modules:
https://foundryvtt.com/packages/monks-player-settings
https://foundryvtt.com/packages/SocketSettings
https://foundryvtt.com/packages/force-client-settings

my choice is for monks-player-settings.
