### ISSUE TITLE
Skillcheck SVGs with proxy

### ISSUE THREAD

**Issue by BohnSeb** [ShoyuVanilla/FoundryVTT-Chat-Portrait#113]
### Environment Details

* Foundry VTT Version: 9, Build 280
* Operating System: Ubuntu 20.04
* How Are You Using Foundry: Chrome and Firefox over Webserver
* Which Game System: DnD5e 1.6.3
* Modules Enabled?: yes: Better Rolls for 5e, Actually private Rolls

### Issue Description

When using a reverse Proxy with Foundryvtt, the SVGs of Skillchecks like "Insight" can't be loaded, because of the chat-portrait module ignoring the "routePrefix" option in the options.json. This results in the resource getting requested at the wrong uri.

### Example
If the domain is "www.foundryserver.com" the proxy takes all requests to the address "http://www.foundryserver.com/server1" and routes them to "localhost:30000".
The corresponding options.json needs to have the proxyPort, hostname and routePrefix set. In this example the routePrefix would be "server1".
Here is an comparison when rolling an insight check and chat-portrait is trying to load the "insight.svg" resource:
* Expected behaviour: GET http://www.foundryserver.com/server1/modules/chat-portrait/assets/insight.svg
* Present behaviour: GET http://www.foundryserver.com/modules/chat-portrait/assets/insight.svg

The chat-portrait module should include the "routePrefix" option from the options.json into their request-Strings.
![vtt-options](https://user-images.githubusercontent.com/29735145/187075939-f149665b-89da-4bcf-8656-fa9b4099743f.png)

**Comment by BohnSeb** [comment]
![Missing-insight-icon](https://user-images.githubusercontent.com/29735145/187076040-4504c5e5-82fd-49e6-ab5a-09d0f299256b.png)
Thats what it looks like in the chat

**Comment by p4535992** [comment]
Should be solved with 0.8.0, try out and let me know
