### ISSUE TITLE
Bug: Some images use absolute rather than relative paths

### ISSUE THREAD

**Issue by Lrizika** [ShoyuVanilla/FoundryVTT-Chat-Portrait#115]
**Module Version:** v0.7.4

Some image paths use relative (`/image/path.ext`) rather than relative (`image/path.ext`) paths, which causes those paths to be incorrect for Foundry installations that are not at the base path of the server (e.g. https://myserver.tld/foundry/).

Current behavior:
![Screenshot from 2022-09-04 17-40-33](https://user-images.githubusercontent.com/8592308/188342706-b670cf49-8015-4a95-a6f1-b85d2eeadfa9.png)

Expected behavior:
![Screenshot from 2022-09-04 17-40-43](https://user-images.githubusercontent.com/8592308/188342722-8a36c381-1591-411b-a7ca-947b3c234412.png)

This can be fixed by removing the preceding slash from paths.

**Comment by p4535992** [comment]
Should be solved with 0.8.0, ty for the hint
