### ISSUE TITLE
portrait not showing in V10

### ISSUE THREAD

**Issue by oestred** [ShoyuVanilla/FoundryVTT-Chat-Portrait#116]
Hello. I am testing out the latest V10 and found that the background chat color settings from chat portraits work, which is nice, but the actual portraits do not show.

I wasn't sure if chat portrait is being updated for V10 or not.

Thank you

**Comment by p4535992** [comment]
I made some test , try out 0.8.0 and let me know if the issue persist..
What did you mean with portrait ? The token image, the avatar image or the user player image reference ?

**Comment by oestred** [comment]
Updated to the 0.8.0. I had to do the reset settings to default option of the module settings and then it worked normally.

Thank you!
