### ISSUE TITLE
Incompatibility with Monk's Enhanced Journal: Visual distortion of shop purchase chat message

### ISSUE THREAD

**Issue by Athemis** [ShoyuVanilla/FoundryVTT-Chat-Portrait#117]
**Module Version:** v0.7.4

**Describe the bug**
When Chat Portrait and [Monk's Enhanced Journal ](https://github.com/ironmonk88/monks-enhanced-journal) are both active, a distortion of the chat message which asks the GM to confirm a purchase in a shop (part of Monk's Enhanced Journal) occurs (see attached images).

**To Reproduce**
1. Activate both Chat Portrait and Enhanced Journal
2. Create a shop and set it up to need confirmation by a GM upon purchase
3. Let a player purchase an item
4. Observe chat message

**Expected behavior**
Properly aligned images in chat message

**Screenshots**
***With Chat Portrait***
![purchase_with_chat_portrait](https://user-images.githubusercontent.com/552653/191692017-9afbddda-041d-4590-9600-9ffc2488c049.png) 
***Without Chat Portrait***
![purchase_without_chat_portrait](https://user-images.githubusercontent.com/552653/191692032-bc2be883-5b03-472e-bcb1-46f4b374cfa3.png)

 - Browser: Firefox 105 / Chromium 105
 - Foundry Version: v9 (DS4 system does not support v10 yet)
 - System: DS4
 - Module version: 0.7.4 (Monk's Enhanced Journal: 1.0.65)
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? Yes, it's a clear interaction between Chat Portrait and Enhanced Journal (all other modules deactivated, problem persists).

**Additional context**
I don't know if this is something primarily triggered by something Chat Portrait or Enhanced Journal does and is better fixed here or in Enhanced Journal. Hence I will cross-post this on Enhanced Journal issue tracker as well [ironmonk88/monks-enhanced-journal/issues/389](https://github.com/ironmonk88/monks-enhanced-journal/issues/389).

**Comment by p4535992** [comment]
should be fixed ty for the ticket.
