### ISSUE TITLE
Improve position of flavour text

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#119]
The flavour text currently appears underneath the token, which looks a bit unsightly

![image](https://user-images.githubusercontent.com/898086/192278472-7df36022-e129-49fe-b766-9dff1a8ba8b8.png)

There is room under the name for this flavour text to appear, which would look much nicer E.g... (mock up)...

![image](https://user-images.githubusercontent.com/898086/192279341-d03d5fa4-36ab-42be-9f22-596c8275f50c.png)

There is a setting to make the flavour text appear next to the name, but this has multiple issues...

1. There is no space between the end of the name and the start of the flavour text
2.  When the actor name or flavour text are quite long, as the time and trash button wrap onto the next line, instead of staying in the top right hand corner....

![image](https://user-images.githubusercontent.com/898086/192280055-63f66810-9e56-40d8-956b-cb1394ced29f.png)

**Comment by p4535992** [comment]
this issue is no longer resolvable , because i decide to tweak the html structure witht the last release for a better maintance mutlisystem.

**Comment by cs96and** [comment]
Unfortunately the new layout is even worse than the old one.  Even with a short name, the timestamp and trash icon are bumped to a new line below the portrait image...

![image](https://user-images.githubusercontent.com/898086/196206172-fd17088b-03de-44d8-9b50-e2dc8cd657e1.png)
