### ISSUE TITLE
PF2e Styling gets janky with a wider-than-standard sidebar

### ISSUE THREAD

**Issue by esheyw** [ShoyuVanilla/FoundryVTT-Chat-Portrait#128]
I use Sidebar Resizer to expand my sidebar, usually to ~450px, because it feels more comfortable on a 1440p screen to me. This worked pretty well until recently, and now it's a little odd. here's without chat portrait: 
![](https://i.imgur.com/dyds7oE.png)
and here's with: 
![](https://i.imgur.com/H627UJX.png)
with my full setup, so including Chat Timestamp and DF Chat Enhancements, and Small Visual Tweaks (that last one is providing the Private marker), here's a short video of what happens on expansion/contraction:
https://gfycat.com/SelfreliantLividAsianwaterbuffalo
now in from that (gm) side at least, everything works great at 300px wide, and only breaks if wider.
from the player side, the messages can be broken even at 300px: 
https://gfycat.com/FarPlainClownanemonefish

I get that you can't cover *every* edge case, but if this was solveable so stuff stayed left aligned and in the right vertical order, I'd very appreciate it. :)

**Comment by p4535992** [comment]
The project is not here anymore  (read the README of the project) i open your issue here: https://github.com/p4535992/foundryvtt-chat-portrait/issues/25

**Comment by esheyw** [comment]
didn't expect a fix overnight 😂 that seems to work, thank you!
