### ISSUE TITLE
Shrunken images? (feature request)

### ISSUE THREAD

**Issue by MEBonham** [ShoyuVanilla/FoundryVTT-Chat-Portrait#14]
Hi, the default 36px image size in this module wastes a little bit of screen real estate. But if I make the setting smaller than 36, the module cuts off the top and bottom of the Actor's artwork, rather than shrinking the image like I expected. Could the shrinking be implemented instead of the cutting off the top and bottom?
![Screenshot 2020-09-17 063106](https://user-images.githubusercontent.com/25208263/93470616-6bd04d00-f8af-11ea-8c12-773167e6e932.png)

**Comment by ShoyuVanilla** [comment]
Solved in 0.2.0
