### ISSUE TITLE
"Display Chat Flavor Text Next to Portrait

### ISSUE THREAD

**Issue by Mr-Monocyte** [ShoyuVanilla/FoundryVTT-Chat-Portrait#19]
I don't think I'm getting the correct display when I select this.

Attached is an image of what I get when I check that box. This is with no other modules installed and only Foundry 0.6.6 and the latest version of the Pathfinder 2e system.

Aren't I supposed to be seeing the "Perception Check" and the blue bonus summary boxes to the right of the character portrait?

![2020-10-06 (1)](https://user-images.githubusercontent.com/68182688/95252055-4ad58a80-07d1-11eb-9af7-b3803b9f5408.png)

**Comment by SepSepone** [comment]
I have a similar issue with the Chat Flavor Text.
If I use a roll directly from the character sheet (Shadowrun 5e game system) it always shows the character's name. And when an item in the Hotbar is used, the item name is shown. Regardless if Chat Flavor Text option is checked or unchecked. Maybe Chat Flavor means something else? But I can't figure out what it's for...

**Comment by esparen** [comment]
I have the a similar issue with the pathfinder 2e System.
It seems that the CSS for the icon is broken in the chat timeline, with the token appearing bellow the name, between the the skill 
 check and the result.
![image](https://user-images.githubusercontent.com/72260390/102091878-29f76a00-3dfe-11eb-873a-5ccccdbbd6ad.png)

**Comment by p4535992** [comment]
Can you check if this issue is fixed with version 0.2.6 ?

**Comment by SepSepone** [comment]
Thx p4535992 for continuing this mod. The portrait is shown all the time now.
Albeit only as long as the option "Use Token Image" is **unchecked**. but I guess that's a different issue.
Stay safe and enjoy yourself!

**Comment by p4535992** [comment]
So can i close this issue ?

**Comment by SepSepone** [comment]
The only issue I see with this mod is that FoundryVTT itself already shows the character's portrait when a skill is used (or something similar that got no icon/symbol of its own), so we get the same portrait twice (above each other).
As long as an item or special trait with it's own icon is used the mod is neat, showing the portrait above the item's/trait's symbol.
Don't know how deep you wanna dive into this to make it "perfect". As far as the original issue goes, "portrait not shown", I'd call the problem solved.

**Comment by p4535992** [comment]
Yea i leave this in the TODO list.

**Comment by p4535992** [comment]
Hey SepSepone i made a "ImageReplacer" mechanism for avoid the double portrait issue . 
For now i supported the standard labels of Dnd5e, but let me know if for PF2 i miss something.

**Comment by SepSepone** [comment]
Sorry, I don't play PF2, I can only tell you that the "ImageReplacer" works fine for DnD, but doesn't work with Shadowrun 5e.

**Comment by p4535992** [comment]
Yea i just noticed the html card change by the system used, i'm not sure if i will find the time to patch the other system on the short term.

**Comment by SepSepone** [comment]
Any mod support is appreciated, don't stress yourself. It's all about having fun ;)

**Comment by p4535992** [comment]
Well i close this issue, because it's belong to the multisystem  support, if you need support for a specific system just open a new issue.
