### ISSUE TITLE
"Invalid Json Response Body" when updating through Foundry version 0.7.5

### ISSUE THREAD

**Issue by Inmate4251** [ShoyuVanilla/FoundryVTT-Chat-Portrait#20]
After upgrading to the latest stable build of Foundry VTT (0.7.5), the following error message appears when attempting to update the module through the "Add-On Module" screen in foundry.

![image](https://user-images.githubusercontent.com/73290732/96868785-8496ca00-143c-11eb-8b9c-353be8a1af09.png)

**Comment by ShoyuVanilla** [comment]
It's not because of the 0.7.5 update, but I've changed `module.json` path in current version.
Removing the older and reinstralling will work.
