### ISSUE TITLE
Feature Suggestion: Option to hide portrait for GM rolls

### ISSUE THREAD

**Issue by LebombJames** [ShoyuVanilla/FoundryVTT-Chat-Portrait#24]
Currently, the module shows the token for players even if the GM is on private rolls. Having an option to hide the portrait for private rolls would allow GMs to maintain surprise with hidden creatures etc.

**Comment by Monation** [comment]
Would be great if you implemented this! I would love to run this module, but I can't, because when I roll initiative for monsters that are outside of vision, they immediately get spoiled from the portrait.

**Comment by Cussa** [comment]
Hi, there is any update/estimation on this issue?

**Comment by ralph2190** [comment]
Seems like the project hasn't been touched in several months 😢

**Comment by LebombJames** [comment]
@ralph2190 I've found Deepflame's Chat Cards does has this feature and more. I would recommend it.

**Comment by p4535992** [comment]
Done on 0.2.7

![img](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/raw/master/images/unknown_actor_and_weapon_feature.png)
