### ISSUE TITLE
Broken in 0.8.6

### ISSUE THREAD

**Issue by dmaneyapanda** [ShoyuVanilla/FoundryVTT-Chat-Portrait#29]
Does not work in Foundry 0.8.6

**Comment by dmaneyapanda** [comment]
update: works if you use the actor image, does not work if you use the token image instead (i.e. does not work when the first module option is checked ON).

**Comment by Corgi** [comment]
Same issue, and same fix (thanks!). Running on Rasbian Buster.

**Comment by p4535992** [comment]
FIxed with version 0.2.3
