### ISSUE TITLE
Feature suggestion : chat text color as player color

### ISSUE THREAD

**Issue by jbblily** [ShoyuVanilla/FoundryVTT-Chat-Portrait#30]
Hi, I'm not sure this project is still working, but I would like to suggest you to add an option to change chat color as player color.
This can make chats more easier to identify.
Thank you for your hard work.

**Comment by p4535992** [comment]
I don't think we need this, we can just use the background and border option .

![img](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/raw/master/images/background_color_feature.png)
