### ISSUE TITLE
Feature suggestion : OOC portrait as player avatar

### ISSUE THREAD

**Issue by jbblily** [ShoyuVanilla/FoundryVTT-Chat-Portrait#32]
Hello, thank you for your hard work.
In players list, each players can configure their 'player avatar'.

I think it would be great if this module change OOC chat's portrait into 'player avatar'.
Currently, it just shows unknown man icon.
Please consider this suggestion. thank you.

**Comment by p4535992** [comment]
Done in 0.2.7 give a try it's a new module settings.

**Comment by jbblily** [comment]
Thanks, but it ignores token/actor's img... However thank you for your hard work.

**Comment by p4535992** [comment]
Il make some check maybe i miss something

**Comment by p4535992** [comment]
Hey 'jbblily' try out the version 0.2.10 and tell me if is all right now!

**Comment by jbblily** [comment]
Thanks!!! 
Oh... I got the problem
I think when I am GM it ignores actor's icon and only shows GM's player avatar
When I am a player, it works fine.
Can you fix this too? because I have so many npc's to act :D

**Comment by p4535992** [comment]
Strange the use case should be correct. Can you tell me what system game are you using ?

**Comment by p4535992** [comment]
Try out the version 0.2.12 and let me know if is correct now. 
Note : for lack of time the module is ben focused on support the system dn5e

**Comment by jbblily** [comment]
Thanks it works! 
It's a late answer but I usually use Kamigakari or Cthulu 7th system
Sorry for taking your precious time!

**Comment by p4535992** [comment]
Perfect.
I'm sorry, but for support for other systems you will probably have to wait a long time. I don't know if I'll find the time.
