### ISSUE TITLE
Releases since 0.2.1 aren't public

### ISSUE THREAD

**Issue by Doresain** [ShoyuVanilla/FoundryVTT-Chat-Portrait#34]
Hey @ShoyuVanilla , thanks for the great module.

You may not be aware, but it looks like something has gone wrong with your release process, and releases since 0.2.1 aren't accessible in Foundry. (https://foundryvtt.com/packages/chat-portrait/) 

See the conversation in Discord here: https://discord.com/channels/687213225225355296/694659543052976268/856658977697562634

Looking forward to taking advantage of all your cool new features! :)

**Comment by Doresain** [comment]
Woops, just noticed that ShoyuVanilla handed this off and @p4535992 is running the show now - FYI. :)

**Comment by cs96and** [comment]
It looks like the releases are in the `package` directory of the repository.

**Comment by p4535992** [comment]
Fixed finally
