### ISSUE TITLE
Bug: Portraits disappear from chatlog when refreshed

### ISSUE THREAD

**Issue by jbblily** [ShoyuVanilla/FoundryVTT-Chat-Portrait#35]
### Environment Details

* Foundry VTT Version: 0.8.7
* Operating System:  Linux
* How Are You Using Foundry: Chrome
* Which Game System: Kamigakari, cthulu 7th, etc
* Modules Enabled?: [no]

### Issue Description

Portraits disappear after refreshing the world.

![Honeycam 2021-06-22 12-57-09](https://user-images.githubusercontent.com/18694887/122861093-d429ee80-d359-11eb-9972-a0d3a1233814.gif)

**Comment by p4535992** [comment]
Fixed with 02.12
Note : for lack of time the module is ben focused on support the system dn5e
