### ISSUE TITLE
Installing via Foundry package manager installs old version

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#38]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: n/a
* Modules Enabled?: n/a

### Issue Description

If you install Chat Portrait using the Foundry package manager, then it installs the old version of the module (0.2.1), because it still uses the old manifest location.

If you do a manual install using the [new manifest location](https://raw.githubusercontent.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/master/src/module.json) (as described in the readme), then it installs the latest version of the module (0.2.13)

**Comment by p4535992** [comment]
Fixed finally
