### ISSUE TITLE
Portrait Border Shape always resets to "square" when opening the settings

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#39]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: dnd53
* Modules Enabled?: no

### Issue Description
1. Open the Chat Portrait settings
2. Change Portrait Border Shape to "none" or "circle"
3. Type a message and notice that the settings has been honoured
4. Re-open the Chat portrait settings
5. Notice that the border shape has reset to square
6. Save the settings
7. type a message and notice that the portrait now has a square border

Its a bit of a pain, because you have to remember to change the setting back to "none" or "circle" every time you open the settings.

**Comment by cs96and** [comment]
It looks like the same issue happens with the "Display setting" drop down as well.

**Comment by p4535992** [comment]
Should be fixed in 0.2.14 version
