### ISSUE TITLE
Feature request: Don't display portrait on out-of-character messages

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#42]
At the moment, out-of-character chats end up displaying the "mystery man" icon.  It would be nice if there was an option so that no chat portrait is displayed on out-of-character messages...

![image](https://user-images.githubusercontent.com/898086/124263756-908a6e00-db2b-11eb-8134-e222ca25ed0f.png)

**Comment by p4535992** [comment]
So you just want a module settings like "Not styling OOC Message"?

**Comment by cs96and** [comment]
Yeah, basically.  I'm sure the old 0.7 based version used to do this
automatically.

**Comment by p4535992** [comment]
Add some additional module setting on version 0.3.0
