### ISSUE TITLE
Name of player - can't turn off.

### ISSUE THREAD

**Issue by RavenknightDM** [ShoyuVanilla/FoundryVTT-Chat-Portrait#44]
Hiya, just noticed that the player's name is always shown in the chat since the last update. I wonder if we could add another setting for this to keep this optional. ( It kinda takes you out of the scene if you're playing in text.

**Comment by coolfox09** [comment]
Would also like to ask if this can be turned off and made optional as well as a lot of the character names are long and with the player names next to it, it causes it to extend too long and wrap the text. Plus like the above user said, it takes people out from the immersion.

**Comment by p4535992** [comment]
Fixed on 0.3.1 by default is set to false
