### ISSUE TITLE
Issue: Initiative Asset Missing

### ISSUE THREAD

**Issue by Nargath** [ShoyuVanilla/FoundryVTT-Chat-Portrait#46]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 0.8.8
* How Are You Using Foundry: Local Host
* Which Game System: dnd5e
* Modules Enabled?: yes

### Issue Description

The asset that is meant to show up on an initiative roll is missing from the asset folder, resulting in the unknown symbol showing up.
Also I have looked on the repository, and cannot see it in that asset folder either.
![Missing Initiative](https://user-images.githubusercontent.com/5538979/124385011-47970d00-dd17-11eb-9661-86fef27d6465.png)

**Comment by p4535992** [comment]
Fixed on version 0.3.4
