### ISSUE TITLE
Request: ImageReplacer for Long and Short Rests

### ISSUE THREAD

**Issue by Nargath** [ShoyuVanilla/FoundryVTT-Chat-Portrait#47]
It would be cool to see a resting-like icon for when players are triggering either a long or short rest and it displays in chat.
This is for dnd5e

Some examples:
Long Rest: https://game-icons.net/1x1/delapouite/person-in-bed.html
Short Rest: https://game-icons.net/1x1/delapouite/wooden-chair.html (signifying just sitting down for a bit)

**Comment by p4535992** [comment]
Fixed on version 0.3.4 (ty for the images link)
