### ISSUE TITLE
Portrait is not displayed on stream page

### ISSUE THREAD

**Issue by drdwing** [ShoyuVanilla/FoundryVTT-Chat-Portrait#48]
I used Printable /stream module to save chat log.
Stream page displayed portrait but now it doesn't. 😢

fvtt v0.8.8
chat portrait v0.3.0

**Comment by p4535992** [comment]
That module has been deprecated (and abandoned) for more than a year, if you need to save the logs use the module https://foundryvtt.com/packages/df-chat-enhance
