### ISSUE TITLE
Font Class of the Styling

### ISSUE THREAD

**Issue by coolfox09** [ShoyuVanilla/FoundryVTT-Chat-Portrait#49]
Hi! I really appreciate that you have an option that allows for thicker text so it's easier to read for some cases, however, in my case, it actually makes the game MUCH harder to read. I was wondering if there could be an option to not change the css class and make it optional for the "better" text. I do love that you can change the font size which is VERY helpful, but the thickness makes it harder to read in my game. Thank you!

**Comment by p4535992** [comment]
You are right, everyone should be free to use their own custom text , added the module setting on version 0.3.6

**Comment by coolfox09** [comment]
> You are right, everyone should be free to use their own custom text , added the module setting on version 0.3.6

Just wanted to say thank you so much for all your hard work and the frequent updates!
