### ISSUE TITLE
Color borders only on the post, but not the chat portrait

### ISSUE THREAD

**Issue by apoapostolov** [ShoyuVanilla/FoundryVTT-Chat-Portrait#5]
Thank you for creating this excellent mod. I haven't seen it shared on the Discord yet.

Please add an option to turn on off the color border around the token portrait because it looks a bit too much color that takes too much color focus from the character image. It is also too thick. instead, add a very thin black border, maybe at pixel or two. 

In the image below, the character's portrait looks poor when so overwhelmed by his chosen green color. 

![image](https://user-images.githubusercontent.com/4083812/83977650-c9e1b180-a90a-11ea-90e5-0daf1c40cbde.png)

**Comment by ShoyuVanilla** [comment]
Solved in 0.2.0
