### ISSUE TITLE
"Display Chat Flavor Text next to Portrait" has bad formatting

### ISSUE THREAD

**Issue by GambetTV** [ShoyuVanilla/FoundryVTT-Chat-Portrait#51]
This should probably be called "DISABLE Chat Flavor Text next to Portrait", but that's fine. When using D&D5e and disabling this, the formatting becomes weird. The Token name falls beneath the portrait instead of the side of it, it completely loses functionality with the Chat Message Accessibility Indicators mod, and it places the Skill Check text directly next to the Token name with no space.

Ideally I'd like a way to just disable the special Icons you use for Skill and Ability checks, but otherwise leave the formatting alone.

**Comment by p4535992** [comment]
The module [Chat Message Accessibility Indicators](https://github.com/schultzcole/FVTT-Chat-Message-Accessibility-Indicators), it's not been developing for more than a year the last release was for FoundryVTT 0.6.2 so some incompatibility is not to be excluded, but I was unable to replicate your use case are there other active modules that could cause the problem?

**Comment by GambetTV** [comment]
![image](https://user-images.githubusercontent.com/72000497/124689103-ed788200-dea5-11eb-975e-90d1fc6d2c4e.png)

The top image is the messed up one, and shows the weird formatting. That is with "Display Chat Flavor" checked. The bottom one is with it unchecked, and looks much cleaner, but has the icon that I'd like to get rid of.

**Comment by GambetTV** [comment]
BTW, the Chat Message Accessibility Indicators I'm using is the one posted to the Foundry Website, https://foundryvtt.com/packages/chat-indicators here, and was updated 3 weeks ago, and should be compatible up to 0.8.6

**Comment by p4535992** [comment]
That for me has always been a misunderstanding  of Foundry... the entry "last update" refers to the update/refresh on the foundry server not the code ... if you follow the link to the project (https://github.com/schultzcole/FVTT-Chat-Message-Accessibility-Indicators) the version 1.0.0 is not been touched for 13 months.

If you click on the "[Manifest Url](https://raw.githubusercontent.com/schultzcole/FVTT-Chat-Message-Accessibility-Indicators/1.0.0/module.json)" you can read it was developed for Foundry 0.6.2, but the project is so simple (as chat portrait only edits css and html) that it works well even with 0.8.6.

**Comment by p4535992** [comment]
Can't replicate your issue try the new 0.3.9 if the issue persist i need your full module settings for try to replicate this.

**Comment by GambetTV** [comment]
0.3.9 fixed this issue! Thanks!
