### ISSUE TITLE
Doing Ability Checks/Saves causes Portrait to revert to Player Token, not Actor/Character token.

### ISSUE THREAD

**Issue by GambetTV** [ShoyuVanilla/FoundryVTT-Chat-Portrait#52]
Using D&D5e, if anyone, GM or Player, roll a skill check for a token, the output to the chat makes it appear like it was the Token that rolled it, which is what it should be, so that I can keep track of who is rolling. When I do the same thing with Ability Checks or Saving Throws, it instead just puts the Player Name, and puts my player token on the display, with literally no way of telling which character token was rolling.

**Comment by GambetTV** [comment]
On further review this seems to be some kind of incompatibility with the Midi QOL mod. I am completely unclear on what would be causing the issue, whether it's on your end or theirs, but messing around with settings in both modules doesn't seem to fix it.

**Comment by p4535992** [comment]
Should be fixed (partially) with 0.3.9

**Comment by GambetTV** [comment]
Unfortunately not. Attack Rolls, spells, and skill checks all work fine, but using Ability Checks/Saving Throws (as in, clicking on STR or DEX or any of the ability scores and selecting either Ability Score or Saving Throw) causes my Username to make the roll, with no indication as to which token I am rolling for. 

Disabling the Midi QOL module fixes the issue completely. However, I suspect the bug is with your module, as your module had been working with Midi QOL fine until the most recent update I believe, and Midi QOL hasn't been updated for a month I think.

**Comment by p4535992** [comment]
Its seem the version 0.8.31 of  Midi solve the issue,  give me confirmation

**Comment by GambetTV** [comment]
Yep! It works now, thanks!
