### ISSUE TITLE
Chat Portrait for GM?

### ISSUE THREAD

**Issue by TheFabulousIronChef** [ShoyuVanilla/FoundryVTT-Chat-Portrait#55]
Is there a way for the GM to have a chat portrait instead of mystery man?

**Comment by p4535992** [comment]
If you set a avatar and check the 'use avatar image' you should see the avatar image (but the option is applied to player too)

**Comment by TheFabulousIronChef** [comment]
> If you set a avatar and check the 'use avatar image' you should see the avatar image (but the option is applied to player too)

Not sure what you mean by "set a[n] avatar." Where? I feel like only players can set an avatar.

**Comment by p4535992** [comment]
Ok I have to better rename the settings to differentiate the player avatar from the character avatar ...

You can set a avatar for the Gamemaster player, checkout the image

![img](https://i.imgur.com/p6GcuOL.png)

The module should use that image by default  with the module setting 'Use avatar image' active, but for your specific use case i would not know how to handle it, probably the best thing to do is add an additional option to use the player avatar (and not the character avatar), but only for GMs for now see if this solution is fine.

**Comment by TheFabulousIronChef** [comment]
Ahhhhhhhhhh, I see it now. Thank you!

**Comment by TheFabulousIronChef** [comment]
That totally solved it. I had no idea there was a user configuration option. D'oh!
