### ISSUE TITLE
Bug: Chat Portrait not working on /stream tab

### ISSUE THREAD

**Issue by Ghostdesu** [ShoyuVanilla/FoundryVTT-Chat-Portrait#56]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows 10
* How Are You Using Foundry: Firefox
* Which Game System: dnd5e
* Modules Enabled?: yes, Chat Portrait

### Issue Description
Chat Portrait is missing entirely from both OOC and IC messages in /stream 

Screenshot from in-game chat window:
![image](https://user-images.githubusercontent.com/31375910/125523129-da0e6a34-4e35-4c6d-8f32-c9f37fcfb037.png)

Screenshot from /stream:
![image](https://user-images.githubusercontent.com/31375910/125523145-a48ecf2e-d4af-415c-af32-689968390546.png)

**Comment by p4535992** [comment]
Just to be sure this is the module [Foundry-Stream-Module](https://github.com/TabletopsAndAnvils/Foundry-Stream-Module) you are trying to use ?

**Comment by Ghostdesu** [comment]
Nope, I made an empty game to test this. 

The /stream I'm referring to is <foundrylink>/stream as opposed to <foundrylink>/join or <foundrylink>/game for example. 
It's the separate chat log, which as far as I can tell is core functionality.

**Comment by p4535992** [comment]
Mmmh , i don't think i can solve this one, because the html i rendered is after the "createChatMessage" event captured from the stream...

**Comment by Ghostdesu** [comment]
Sorry for the late reply, I actually think being able to toggle it for stream would be pretty useful since in my case I primarily need it there for archiving logs, so that would be great if you could do it.

**Comment by p4535992** [comment]
For archive logs is better https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-chat-enhance
