### ISSUE TITLE
Token portrait does not change even if the token do.

### ISSUE THREAD

**Issue by RavenknightDM** [ShoyuVanilla/FoundryVTT-Chat-Portrait#57]
Hi, thanks for the mod!
I've noticed that the chat-portrait now only show the prototype token picture for the speaker even if you change the image once the character is out on the board.  Changes to token name are recognized without error but the picture shown is always the original prototype.

---
Foundry 0.8.8, D&D 1.3.6, CP 0.3.11

**Comment by p4535992** [comment]
Please pass me the settings configuration of the module you are using. Thank you.

**Comment by RavenknightDM** [comment]
![Chat 1](https://user-images.githubusercontent.com/53635985/125659591-ab85f2f8-a1a0-42e0-b009-e8cdb4463ebb.png)
![Chat 2](https://user-images.githubusercontent.com/53635985/125659600-c83a1b2a-595d-4219-a761-0634942e11f7.png)

Here we go.

**Comment by p4535992** [comment]
Wow didn't notice that , should be fixed on 0.3.12
