### ISSUE TITLE
Portait shows a broken image when using token wildcards, and Better Rolls is enabled

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#58]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows
* How Are You Using Foundry: Edge
* Which Game System: dnd5e
* Modules Enabled?: BetterRolls, libWrapper

### Issue Description

If you set Chat Portrait to use the token image, and the prototype token is set up to use wildcards, then the portrait shows a broken image.  However, this only happens when Better Rolls is also enabled.

![image](https://user-images.githubusercontent.com/898086/125868544-989861fa-902c-4491-96e7-f39e7ea3bf46.png)

![image](https://user-images.githubusercontent.com/898086/125868761-691b3fae-c58d-444a-a959-69397738b717.png)

**Comment by cs96and** [comment]
Also, I just noticed that this only happens when rolling from the sheet (e.g. clicking on a skill check, saving throw, weapon attack etc).  If I type a roll manually into the chat box, it works fine.

**Comment by p4535992** [comment]
When you say the "token is setup to use wildcards" you mean the use of this module [FVTT-TokenHUDWildcard](https://github.com/javieros105/FVTT-TokenHUDWildcard) ?

**Comment by cs96and** [comment]
https://foundryvtt.com/article/tokens/

On the Image tab of prototype token page, you can enter a path that contains a wildcard and check the "Randomize Wildcard Images" box.  E.g. if you enter the image path as...
```
path/to/image*.png
```
then `path/to/image1.png`, `path/to/image2.png` and `path/to/image3.png` could all be used as token images.  When the actor is dragged onto a scene, one of the images is selected at random.  You can then also manually select which one you want  using a drop down on the Image tab of the token config.

The Token HUD Wildcard module is just a convenience module that makes it easier to switch between the different images.  I do use that module, but the bug occurs even when that module is disabled.

**Comment by p4535992** [comment]
KK didn't know that, i will checout!

**Comment by p4535992** [comment]
Ok it's bug of 'Better Roll' , i don't know why , but that module destroy the info on the hook 'createChatMessage'
Here the workflow:

'preCreateChatMessage'  // all the information are fine
'createChatMessage' // here mdi qol, Better roll and others modules work with their stuff in this case Better Roll
'renderChatMessage' // here come chat-portrait, but the info i expected are null or undefined

if i disable better roll the info are fine like in the 'preCreateChatMessage'  hook.

There is no solution on my side, but i made a little patch on the version 0.4.0 where the token image is fine when you throw some dice, but is a volatile information when you refresh the page you will see all the broken image.

Try to open a issue to the Better Roll module and link this issue.

**Comment by p4535992** [comment]
It's seem the last update of Better Roll fix the issue.
