### ISSUE TITLE
BUG: Players' OOC messages use character image instead of player avatar

### ISSUE THREAD

**Issue by Ghostdesu** [ShoyuVanilla/FoundryVTT-Chat-Portrait#59]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows
* How Are You Using Foundry: Firefox
* Which Game System: dnd5e
* Modules Enabled?: yes, latest version of Chat Portrait

### Issue Description
Players' OOC messages use character image instead of player avatar

What it looks like right now:
![image](https://user-images.githubusercontent.com/31375910/126011600-0c220d36-d975-4642-997d-a6ace5b807ef.png)

What it should look like:
![image](https://user-images.githubusercontent.com/31375910/126011715-a9019896-41ea-453a-85c5-3fe7f2d0aec4.png)

The bug does not affect GM players.

Note: This issue was not present in 0.3.10 and I believe was introduced in 0.3.11

**Comment by p4535992** [comment]
Should be fixed on 0.4.0
