### ISSUE TITLE
Improved float for the image when a roll post has a subtitle field

### ISSUE THREAD

**Issue by apoapostolov** [ShoyuVanilla/FoundryVTT-Chat-Portrait#6]
Please check whether it is possible for the following roll posts to have both the player name and the roll subtitle "Acrobatic Skill Check" float around the character portrait. 

![image](https://user-images.githubusercontent.com/4083812/83977679-13320100-a90b-11ea-95da-d5159ef4f51a.png)

**Comment by ShoyuVanilla** [comment]
Solved in 0.2.0
