### ISSUE TITLE
Missing portraits + conflict with Monk's Token Bar

### ISSUE THREAD

**Issue by grankless** [ShoyuVanilla/FoundryVTT-Chat-Portrait#60]
* Foundry VTT Version: .8.8
* Operating System: Windows 10
* How Are You Using Foundry: native app
* Which Game System: pf2e
* Modules Enabled?: Yes - Monk's Token Bar involved

https://i.imgur.com/eCxpgtT.png

Pictured is what happens when I have Chat Portraits enabled and attempt to award XP using Token Bar. You can see that there are these big-ass mystery icons next to people in the menu for it. I have made an issue for it https://github.com/ironmonk88/monks-tokenbar/issues/120 here.

However, since updating to Chat Portrait 4.0, all portraits have become that mystery book icon. This is kind of unusable. CP is the only module I use that interacts with portraits in any way.

**Comment by JackaldaJester** [comment]
Also having this issue after updating to 4.0. I don't have Monk's Token Bar enabled so don't know if there was a sudden conflict with something else.

**Comment by p4535992** [comment]
> Also having this issue after updating to 4.0. I don't have Monk's Token Bar enabled so don't know if there was a sudden conflict with something else.

More info please !! Always on PF2 System ?

**Comment by p4535992** [comment]
For a temporary solution just disable the "Image Replacer feature"

**Comment by JackaldaJester** [comment]
Foundry VTT Version: .8.8
Operating System: Windows 10
How Are You Using Foundry: Forge Hosting
Which Game System: dnd 5e
Modules Enabled?: Yes - Multiple enabled (CUB, Midi QoL, etc).

I'm also having the issue where everyone's icons, players and NPCs included, are replaced by the blue book with the question mark on it. I think that's the default image for unknown items? For now I've rolled the module back to 0.3.12 which brings everything back to normal.

**Comment by p4535992** [comment]
Should be all fixed on 0.4.1 version

**Comment by grankless** [comment]
Yup! Works great now. Thanks!

**Comment by p4535992** [comment]
Ok we are faced with a problem of choices in terms of style, by default I have verified (but it is purely my opinion), that the choice of "flex" at the text level is more consistent with most systems. In fact, for PF2 I prefer the first version while you instead the second, but the module still allows you to customize the text model according to your needs in this case you just need to set the "display: block" to restore the default style of PF2 as shown in the figure.

![img](https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/raw/master/images/chat_portrait_feature.png)

**Comment by JackaldaJester** [comment]
Everything working proper, thank you for your work!
