### ISSUE TITLE
Latest release breaks PF2E formatting

### ISSUE THREAD

**Issue by JamzTheMan** [ShoyuVanilla/FoundryVTT-Chat-Portrait#61]
It seems the latest version has the image for the strike and it adds a column of pure blankness under it. I tested in a blank world with latest core/foundry/module.

### Environment Details

> Please share the following basic details about your setup.

![image](https://user-images.githubusercontent.com/8051654/126231322-c9886f88-0a8e-4fc7-af1d-a70a44907567.png)

### Issue Description

With Chat Portrait enabled:
![image](https://user-images.githubusercontent.com/8051654/126231285-88f2adbb-5e13-4876-a46b-6421212e5516.png)

Without Chat Portrait enabled:
![image](https://user-images.githubusercontent.com/8051654/126231353-6c7370ff-2c57-4d90-8348-a0a9198dd7af.png)

**Comment by p4535992** [comment]
Now you are the second dude who hate the flex solution, i must rethink the use case... for now you can set the css styling like in this image it should work for PF2:
![img](https://raw.githubusercontent.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/master/images/chat_portrait_feature.png)

**Comment by p4535992** [comment]
Should be fixed on 0.4.4
