### ISSUE TITLE
« Cannot Read property 'id' » when loading & combat state

### ISSUE THREAD

**Issue by Djahal** [ShoyuVanilla/FoundryVTT-Chat-Portrait#62]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 0.8.6
* Operating System: Windows
* How Are You Using Foundry: Chrome
* Which Game System: D&D 5e
* Modules Enabled?: [yes, no] Maybe a conflict with DnD 5e Helpers.

### Issue Description

Fisrt of all, thank you for all you've done so far and for the involvement you put in Blood n' Guts (can't wait to see it released for 0.8.x :D).
The issue I have was already here in a former release (can't recall), got fixed in the last one and came back for the 0.4.1.
I've seen you're already working on the 0.4.2 so if you're fixing it by now, forget about it :).

When I'm in combat, each time I target a token, I get this error in the console :

![image](https://user-images.githubusercontent.com/80932931/126247653-c341bd05-1de4-4bea-b927-3a6985fa1161.png)

If you need any further info, don't hesitate.

**Comment by p4535992** [comment]
I will look into it, but for Blood and guts maybe you miss the last post [Splatter is the new Blood and guts for 0.8.X](https://github.com/edzillion/blood-n-guts/pull/277#issuecomment-882402813)

**Comment by Djahal** [comment]
Thank you for that :).

And yes I'm already using it and it's cool but I prefer the options provided by B&N. Like the random splatters upon the token...
I've seen that theripper93 is not willing to implement the equivalent so I have the feeling that it is more of a substitution than a real update.
Moreover, I thought you and edzillion were working on updating B&N for 0.8.x, and if it's not the case anymore I do understand, but it feels like a loss to me :P.

Anyway, thanks for all you've done so far.

**Comment by p4535992** [comment]
Should be fixed on 0.4.4
