### ISSUE TITLE
Chat flavor text looks a bit wonky and out of place

### ISSUE THREAD

**Issue by cs96and** [ShoyuVanilla/FoundryVTT-Chat-Portrait#63]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Linux (Debian 11)
* How Are You Using Foundry: Vivaldi
* Which Game System: dnd5e
* Modules Enabled?: no

### Issue Description

When "Display Chat Flavor Text next to Portrait" is enabled, it would previously put this just under the name, but still next to the image.  Since updating from 0.4.1 to 0.4.3, this is now displayed right next to the actor name, without a space, not quite in line, and in a different font size from the name.  It just looks a bit wonky and wrong...

![image](https://user-images.githubusercontent.com/898086/126637618-3c2000ab-0158-4a7c-9f14-6a3c3fe6deb4.png)

Was the flavor moved up next to the name on purpose?  I quite liked it underneath the name, but still next to the image.  If it was done on purpose, can the flavor text at least have a consistent alignment and font size with the name?

**Comment by p4535992** [comment]
Yea i messed up with css for PF2 , i will fix with the next release

**Comment by p4535992** [comment]
Should be fixed on 0.4.4
