### ISSUE TITLE
Text unreadable for some chat cards in PF1

### ISSUE THREAD

**Issue by emdant** [ShoyuVanilla/FoundryVTT-Chat-Portrait#64]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: Windows 10
* How Are You Using Foundry: Chrome (Forge hosted)
* Which Game System: PF1
* Modules Enabled?: yes

### Issue Description

Using Find the Culprit I found that Chat Portrait is changing the color property of some chat cards title text for Pathfinder 1, which makes it unreadable (example below, respectively without and with chat portrait)
![image](https://user-images.githubusercontent.com/30555419/126862150-0fe8582b-fa25-4b05-86c7-90351dfc980a.png)![image](https://user-images.githubusercontent.com/30555419/126862175-91ba7e5f-127c-44ba-8772-55bfb9933ddd.png)

I found out that the problem is that chat portrait is removing the inline style of the element that makes the text white:
```
<h3 class="item-name chat-portrait-text-size-name" style="">
<img src="systems/pf1/icons/misc/magic-swirl.png" title="Cure Serious Wounds" width="40" height="40" class="message-portrait">
Cure Serious Wounds
</h3>
```
While this is the text when the module is disabled:
```
<h3 class="item-name" style="color: white;">Cure Serious Wounds</h3>
```

**Comment by p4535992** [comment]
Should be fixed on 0.4.4
