### ISSUE TITLE
background color with narrator tools

### ISSUE THREAD

**Issue by drdwing** [ShoyuVanilla/FoundryVTT-Chat-Portrait#65]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: (Example 0.5.4)
* Operating System: win 10
* How Are You Using Foundry: Application
* Which Game System: dnd5e
* Modules Enabled?: yes

### Issue Description

> Please provide a description of your issue below. Including console error messages, screenshots or videos can be particularly helpful.

If you check change color of message background, you can see the narration message background color is also changed.
I don't think you did it on purpose. 😊

**Comment by p4535992** [comment]
It was done on purpose, but now I've seen that that module allows you to manage your own CSS, so it doesn't make sense to apply my own CSS on top of it. I will try to correct it somehow

**Comment by p4535992** [comment]
Should be fixed with 0.4.5

**Comment by drdwing** [comment]
![Cap 2021-07-29 03-14-39-726](https://user-images.githubusercontent.com/66671688/127375259-9166c2af-f5ef-4acb-a18e-abf970878b8e.png)
![Cap 2021-07-29 03-18-42-580](https://user-images.githubusercontent.com/66671688/127375267-02fca1a6-f2a2-4164-964a-23f515db2380.jpg)

I really sorry but Chat Portrait mod still change the background color of narration.
Is there something wrong with my module setting?

**Comment by drdwing** [comment]
I think it doesn't seem to work if I set the language setting to Korean. Would you check about that? 😢

**Comment by p4535992** [comment]
Sorry I'm in a hurry, I did a possible bug fixing with version 0.4.6 let me know if it's work

**Comment by drdwing** [comment]
Now it works! Thank you very much!! 😊👍
