### ISSUE TITLE
Initiative roll bugged 0.4.4

### ISSUE THREAD

**Issue by RavenknightDM** [ShoyuVanilla/FoundryVTT-Chat-Portrait#66]
Hi, thanks for the mod. I got a strange issue with ver. 0.4.4. (D&D 54 1.3.6).
Whenever we roll for initiative the token picture is blown up to its original size and clutters the chat.
![Chat Portrait initiative](https://user-images.githubusercontent.com/53635985/126891467-400e1c8c-573a-43a8-b425-8fdf32ba7fd4.png)
( Quite possible that it's related to some of my many other mods. But this didn't happen with last version of CP )

**Comment by p4535992** [comment]
Cannot replicate, can you send me the full module settings ? Ty.

**Comment by p4535992** [comment]
Nevermind found it

**Comment by p4535992** [comment]
Should be fixed on 0.4.5
