### ISSUE TITLE
Background images obscure roll type colouring

### ISSUE THREAD

**Issue by LorduFreeman** [ShoyuVanilla/FoundryVTT-Chat-Portrait#68]
Specifically Line 10-18 in the .css:
```
.chat-message,
.chat-message.emote,
.chat-message.blind {
  background-image: url(../assets/parchment.jpg);
  background-repeat: repeat;
}
.chat-message.whisper {
  background-image: url(../assets/parchment-white.jpg);
}
```

The parchment backgrounds obscoure the chat card colour and make recognizing which roll type it is very hard. In my opinion they should be removed.

![image](https://user-images.githubusercontent.com/72170114/127583182-90e00716-f2ca-486d-8391-02ee71183f72.png) vs  ![image](https://user-images.githubusercontent.com/72170114/127583218-f5ed21e8-d2a7-4a21-ba96-e6d718ef78e1.png)

**Comment by p4535992** [comment]
Should be fixed on 0.4.7
