### ISSUE TITLE
Chat images don't show up

### ISSUE THREAD

**Issue by Kaliyn** [ShoyuVanilla/FoundryVTT-Chat-Portrait#69]
* Foundry VTT Version: 0.8.8
* Operating System: Windows10
* How Are You Using Foundry: Native Application
* Which Game System: Simple World Building, Pathfinder2
* Modules Enabled?: no

First of all, sorry for my bad english, it's not my native language. I'm doing my best.

I recently upgraded from 0.7.9 to 0.8.8. Since the update, the Chat Portrait module no longer works correctly. Some of the options works but the token images are not displayed in the chat as they should be. Same for the message borders colors. I tried many combinations, changing player rights, images, tokens... I tried this with Simple World Building system and Pathfinder2 system.
I asked a friend of mine to create a world with the Simple World Building system in 0.8.8 using the Chat Portrait module. For him, everything works correctly. But we procedeed in the same way to install and use the module.

I tried to completely uninstalling Foundry and all the data from my pc and reinstalling everything, create a new world etc... But it doesn't work.

Any idea ?

![image](https://user-images.githubusercontent.com/88190761/127645030-ca29f019-db69-4593-9779-964d28da012b.png)

**Comment by p4535992** [comment]
Not sure, but i made some bug fix check out version 0.4.7

**Comment by Kaliyn** [comment]
Thanx for the answer. Unfortunately, nothing changes.

**Comment by Kaliyn** [comment]
Edit :
i just tried the module via the player interface on mozilla. It works. But on my native application with GM account, it doesn't works. Maybe something to activate ?

**Comment by Kaliyn** [comment]
Solved. I changed some settings in my firewall.
