### ISSUE TITLE
unkown creatures have portrait hidden

### ISSUE THREAD

**Issue by mistamichal** [ShoyuVanilla/FoundryVTT-Chat-Portrait#7]
If I have the hide creature name option turned on in CUB, then the portrait is also hidden.

Can you fix it so that the portrait will still show even if the players don't know the name of the creature?

**Comment by ShoyuVanilla** [comment]
I'll find out if it is possible.

**Comment by ShoyuVanilla** [comment]
I think in has been solved in 0.2.0 as I cannot reproduce it.
If same problem happens again, please reopen the issue.
