### ISSUE TITLE
[PF1] Applying damage from a chat card focuses the speaker

### ISSUE THREAD

**Issue by envy** [ShoyuVanilla/FoundryVTT-Chat-Portrait#70]
### Environment Details

* Foundry VTT Version: 0.8.8
* Operating System: doesn't matter
* How Are You Using Foundry: both Windows native and running on node on Debian
* Which Game System: PF1
* Modules Enabled?: yes, but Chat Portrait is the culprit as it stops when disabling it and happens when only Chat Portrait is enabled

### Issue Description

PF1 attack chat cards have buttons to easily apply the damage to the selected token. When clicking the button, damage is applied as normal but directly afterwards the selected token is shifted to the speaker of the chat card. This is bad, because when you quickly want to apply damage from multiple attacks you always have to retarget the token.

Here is a picture of the chat card, clicking the "Anwenden" or "Hälfte Anwenden" buttons causes the retargeting.
![grafik](https://user-images.githubusercontent.com/241552/127692592-0ecde9dd-ed2a-448c-a9d5-1b98bf03a4fe.png)

Its also happening when clicking on inline rolls to show their parts which is also kind of annoying.

**Comment by envy** [comment]
Additional Info: This only happens to some attack cards and I was not yet able to determine why.

The "buggy" chat cards have this event handler registered:

![grafik](https://user-images.githubusercontent.com/241552/127698187-e8fa9e66-574d-4c91-8cca-cbcdae3b1c84.png)


But not all chat cards have that handler for some reason...

**Comment by p4535992** [comment]
Should be fixed on 0.4.7

**Comment by envy** [comment]
Yep, fixed. Thanks
