### ISSUE TITLE
Suggestion: whisper colors

### ISSUE THREAD

**Issue by Nedrapter** [ShoyuVanilla/FoundryVTT-Chat-Portrait#72]
The ability to color the chat messages based on the player color is something that really flavors up the chat. However on any darker color, when you receive a whisper, the text is barely legible. Can something be done about whisper or darker colors to reduce this?
example: 
![image](https://user-images.githubusercontent.com/74311190/128154292-52386ec0-ce35-4146-ab37-ebeca9e3d163.png)

**Comment by p4535992** [comment]
Should be fixed on version  0.4.8
