### ISSUE TITLE
Provide option to use 'token name' instead of 'actor name'

### ISSUE THREAD

**Issue by tecknojock** [ShoyuVanilla/FoundryVTT-Chat-Portrait#8]
I use token mold to randomize names so that players cant metagame as much by just knowing what the creature is. That said, unfortunately character portrait says the actor name instead of the token name.

**Comment by ShoyuVanilla** [comment]
<img width="291" alt="Test" src="https://user-images.githubusercontent.com/10542892/86975072-75a04a80-c1b2-11ea-9989-91c2e8a82eaa.png">
This seems not to be related to this module, since it only adds portraits into images.
It does nothing to chat messages' alias.
