### ISSUE TITLE
[BUG] Rolled Tables image bug

### ISSUE THREAD

**Issue by adacosta92** [ShoyuVanilla/FoundryVTT-Chat-Portrait#80]
**Module Version:** v0.5.19

**Describe the bug**
Rolled tables have the image of the first item moved to a weird spot

**To Reproduce**
1. Roll any table with images attached to the table items

**Expected behavior**
The images should be beside the rolled item

**Screenshots**
It looks like this
![image](https://user-images.githubusercontent.com/67127175/138532799-a13eab7c-dd8b-4aaa-ad22-f465ff42e883.png)
It should look more like this
![image](https://user-images.githubusercontent.com/67127175/138532830-1bcb9d74-7f5f-45ff-bd09-cbf9ba7522a1.png)

**Browser:**
 - Chrome

**Foundry Version:** 0.8.9

**Game System:** dnd5e1.5.3

**Additional context**
None

**Comment by p4535992** [comment]
Try out 0.5.20 and let me know

**Comment by adacosta92** [comment]
looksg ood!
