### ISSUE TITLE
[BUG] 5.24 version is broken

### ISSUE THREAD

**Issue by weepingminotaur** [ShoyuVanilla/FoundryVTT-Chat-Portrait#84]
The latest version of Chat Portrait appears to be broken. No module settings appear even when the module is installed and all the Chat Portrait features stopped working. Reinstalling did not fix the problem. Rolling back to 5.23 fixed the problem.

**Comment by p4535992** [comment]
seems to work, (otherwise they would have flooded me with issues), unless you can tell me more than "it's broken" I can't help you.
Any exception on the web console ?

**Comment by weepingminotaur** [comment]
No console errors. It's like the module is just failing to load. But I understand that this isn't the most precise bug request. I'll test over the weekend and check back in. I suspect it's a module conflict.

**Comment by Nedrapter** [comment]
I'm experiencing the same. No error, it's just as if it's not installed, even though it shows installed.

**Comment by p4535992** [comment]
sorry about this, any information is welcome, browser, foundry version, ecc.

**Comment by weepingminotaur** [comment]
Using Chrome on Foundry 0.8.9.

**Comment by Nedrapter** [comment]
Opera, Chrome, Firefox , 0.8.9

**Comment by p4535992** [comment]
are you using the japanese language ?

**Comment by Nedrapter** [comment]
> are you using the japanese language ?

No, english. I did revert back to previous too and worked fine, couldn't figure out anything more.

**Comment by weepingminotaur** [comment]
Just tested tonight with Find the Culprit. Removed all other modules except Chat Portrait 5.24 and the problem persisted. Rolling back to 5.23 fixed the problem. I'm on Chrome 96.0.4664.110 (latest version), Mac OS Big Sur 11.6.1, running Foundry 0.8.9 on the Forge.

**Comment by p4535992** [comment]
k i replicate the error on the forge is something on the cache? not sure about the solution. Uninstall/install the module work for me , updating to a new version work too. I created a new version with no code change just for a refresh of the module. So my advise is uninstall the module and reinstall again. Let me know.

**Comment by weepingminotaur** [comment]
Uninstalling and then installing the new version worked! Now everything displays fine and I can see the module settings for Chat Portrait again. Thank you!
