### ISSUE TITLE
Image missing from elementItemImageList

### ISSUE THREAD

**Issue by Wigginns** [ShoyuVanilla/FoundryVTT-Chat-Portrait#85]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 9.238
* Operating System: Windows
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: dnd5e
* Modules Enabled?: yes, Combat Utility Belt

### Issue Description

Combat utility belt has an option to automate concentration. When this happens it outputs a message to the chatlog detailing who is concentrating and on what.  However, the img for "Concentrator" is undefined. It still shows up in the list of images (`src/module/ChatPortrait.ts: 359 elementItemImageList`) to be parsed in the card but is undefined, creates and error and displays a missing image icon.

![image](https://user-images.githubusercontent.com/3180645/147797207-b8153a23-53c4-46f8-ab5c-44e393a2af1a.png)

![image](https://user-images.githubusercontent.com/3180645/147797256-1698f7fd-e0a8-41a7-9806-b29ba6857a84.png)

I believe this bug is caused by CUB's card formatting in some manner but there may be value in Chat Portrait handling this error in a more graceful manner such as displaying a placeholder or displaying nothing.

I patched my local installation to simply check if `elementItemImage` is defined and if not to just continue to the next image in the list. I'm sure there is a way to do that in typescript but I am having a hell of a time installing the project on my local to try it (likely a problem with my Windows setup -_-)

Edit: Turns out I need to use the node v14 lts 👍

**Comment by p4535992** [comment]
should be patched  with version 0.5.29 let me know.

**Comment by Wigginns** [comment]
Appreciate the quick fix. It no longer generates an error or fills in a with a missing img icon but I get an unknown source still. 

![image](https://user-images.githubusercontent.com/3180645/148090947-c195770f-6efe-4df6-a0ac-e35958d86e50.png)
`<img width="36" height="36" src="" class="message-portrait">`

Again, this is likely a Combat Utility Belt issue more than anything. Personally, I might just show nothing if an image can't be found but I don't feel strongly about it.

![image](https://user-images.githubusercontent.com/3180645/148091276-f31bafa7-58ec-4bc3-a394-b67a05451091.png)

**Comment by p4535992** [comment]
should be patched (again) with version 0.5.31 let me know.

**Comment by Wigginns** [comment]
Looks great! Thanks!
