### ISSUE TITLE
Compatibility with roll of fate

### ISSUE THREAD

**Issue by altair984** [ShoyuVanilla/FoundryVTT-Chat-Portrait#87]
hello, first of all thanks for your work and secondly, would it be possible that this module that I like so much could be compatible with the "Roll of fate" module. when you use both modules the following happens:

![imagen](https://user-images.githubusercontent.com/52784850/148205497-411225b6-c1b0-424a-9aa5-00955e535f8b.png)

Would it be possible to ignore the chat portrait image or something that does not damage the card? thank you very much :D

**Comment by p4535992** [comment]
should be patched with version 0.5.31 let me know.

**Comment by altair984** [comment]
YES  now work perfect, thanks so much :D
