### ISSUE TITLE
[BUG] Module incompatibility with midi qol saving throw panel

### ISSUE THREAD

**Issue by adacosta92** [ShoyuVanilla/FoundryVTT-Chat-Portrait#88]
**Module Version:** v0.5.31

**Describe the bug**
Token images are messed up on midiQOL's saving throw checker

**To Reproduce**
1. using midiQOL, cast a spell that requires multiple tokens to make a save. You need "check saves: GM sees" on.

**Expected behavior**
(obviously WITH the "DM" chat portrait as well)
![image](https://user-images.githubusercontent.com/67127175/148301861-44f9f4b3-0b4e-4d14-8682-234735bf946e.png)

**Screenshots**
current behaviour: 
![image](https://user-images.githubusercontent.com/67127175/148301820-d8572925-dd49-470b-874e-f643c3494679.png)

**Browser:**
 - Chrome 

**Foundry Version:** 
0.8.9

**Game System:** 
dnd5e 1.5.5

**Additional context**
None

**Comment by p4535992** [comment]
@adacosta92 Should be fixed with version 0.5.32. let me know.

**Comment by adacosta92** [comment]
its fixed! :) thanks!!!
