### ISSUE TITLE
[BUG] Messages are improperly modified with the Star Wars system

### ISSUE THREAD

**Issue by wrycu** [ShoyuVanilla/FoundryVTT-Chat-Portrait#90]
**Module Version:** v0.5.35

**Describe the bug**
The first die in the pool is moved in the chat card (to before the flavor text)

**To Reproduce**
1. Use the `Star Wars FFG` system with `Chat-Portrait` module enabled on Foundry 9.x
2. Roll any skill from an actor sheet
3. View the resulting chat

**Expected behavior**
Dice are after the flavor text, not before it.

**Screenshots**
With the module disabled:

![image](https://user-images.githubusercontent.com/4709746/151271380-c3bec4e7-ef03-4984-8f65-7ff231f16b3d.png)

and with it enabled:

![image](https://user-images.githubusercontent.com/4709746/151271414-b106953a-acc9-42c4-b9cf-ebe9bb18cc26.png)

**Browser:**
Edge

**Foundry Version:** 
9.242

**Game System:** 
1.71

**Comment by p4535992** [comment]
should be fixed with version 0.5.36

**Comment by wrycu** [comment]
Confirmed, thanks for the quick turnaround!
