### ISSUE TITLE
An option to center token/actor name vertically 

### ISSUE THREAD

**Issue by Vesselchuck** [ShoyuVanilla/FoundryVTT-Chat-Portrait#92]
How it is now:
![Screenshot_8](https://user-images.githubusercontent.com/70449411/152702538-3c3677c6-b12f-49fe-b299-b461e82dcec4.png)
The better way:
![Screenshot_88](https://user-images.githubusercontent.com/70449411/152702619-84490325-4cd0-4173-83bc-2cfcab613585.png)

**Comment by p4535992** [comment]
You can do that by using the css module settings, or you can specify what system are you using and i will aplly by default for that system, on the README you can find the details about the **CSS CUSTOMIZATION** settings.

**Comment by Vesselchuck** [comment]
> You can do that by using the css module settings, or you can specify what system are you using and i will aplly by default for that system, on the README you can find the details about the **CSS CUSTOMIZATION** settings.

I am using PF2E system and I don't even have a single clue how to do any **CSS CUSTOMIZATION**. So it would be really great if you could do that.

**Comment by Vesselchuck** [comment]
> You can do that by using the css module settings, or you can specify what system are you using and i will aplly by default for that system, on the README you can find the details about the **CSS CUSTOMIZATION** settings.

Hey, I've been told that this should help me center those:
```
.message .message-header {
    align-items: center;
}
```
So I've put that code in one of those boxes in the module settings, but it doesn't work.
![image](https://user-images.githubusercontent.com/70449411/153072872-6bd2766a-883a-4dda-bb7e-cece7ef68119.png)
![image](https://user-images.githubusercontent.com/70449411/153072830-42dd2e9b-22e8-4597-b688-d53fd6f6f8c9.png)

**Comment by p4535992** [comment]
i already solved for the next release, for pf2e should be  enough `margin:auto` if you want to try

**Comment by Vesselchuck** [comment]
> i already solved for the next release, for pf2e should be enough `margin:auto` if you want to try

Thanks a lot!
