### ISSUE TITLE
[BUG] Conflict with Roll of Fate module

### ISSUE THREAD

**Issue by Fridan99** [ShoyuVanilla/FoundryVTT-Chat-Portrait#93]
**Describe the bug**
Apparently there is an interaction between the roll of fate and the chat portrait. When used together, the roll of fate letters cannot change color. 

I am not sure which module creates the actual conflict, chat portrait or roll of fate. 

**To Reproduce**
1. Go to 'install Roll of Fate and Chat Portrait modules'

**Expected behavior**
No conflict with modules. 

**Screenshots**
![text](https://user-images.githubusercontent.com/86131373/153010827-d6335e6c-cb4d-44c6-8b21-8073376db51c.jpg)

**Browser:**
 NO. App itself

**Foundry 0.9.249**
**System dnd5e 1.5.7**
**Roll of Fate 0.4.6**
**Chat Portrait 0.6.0**

**Comment by p4535992** [comment]
I cannot solve this until i get some reference for the roll-of-fate chat message.
https://github.com/Handyfon/roll-of-fate/issues/15
