### ISSUE TITLE
[BUG] Chat Images works for players but not GM unless in combat

### ISSUE THREAD

**Issue by MagicOriole** [ShoyuVanilla/FoundryVTT-Chat-Portrait#95]
Chat Images for GM work ONLY during combat.
Ive tested this exstensively. 
Happens with just chat images enabled and nothing else.

**Comment by p4535992** [comment]
Work fine on my dnd5e world, are you using another system than dnd5e ? and what did you mean by not work ? is not show the image and print the url of the image on the chat ?

**Comment by MagicOriole** [comment]
DND 5E
Version 9 BUILD 255
Works on player side but not GM side
![image](https://user-images.githubusercontent.com/96490347/157765773-1b6f2674-e87b-4f74-9771-ca1567b00f75.png)
Picture to show what I mean by not work.
But if combat starts its working correctly.
Chat images settings gone through over and over and issue persists.

**Comment by p4535992** [comment]
sorry I thought you were talking about the "[Chat Images](https://foundryvtt.com/packages/chat-images)" module, the error is still strange can you pass me the module settings? You can use the form https://foundryvtt.com/packages/forien-copy-environment to do this first.

**Comment by MagicOriole** [comment]
![image](https://user-images.githubusercontent.com/96490347/157947996-96a1771f-8f47-45a4-881b-186f13b8ca0a.png)

![image](https://user-images.githubusercontent.com/96490347/157948062-e457101d-7e78-4d51-956b-69cbe4e40507.png)

![image](https://user-images.githubusercontent.com/96490347/157948093-fcf53b10-e4d4-4e42-ae30-4d62f114e777.png)

**Comment by p4535992** [comment]
ty for the contribution i will check out this week end

**Comment by MagicOriole** [comment]
Thanks @p4535992 !

**Comment by p4535992** [comment]
I'm not sure why you end up with this combination, but you must disable the "Apply patch for 'PreCreateChatMessage", if not for very special case .
You must setup these setting for visualize the portrait :
"Display chat message of type XXX"

when i have time i will convert some of this setting on the player side, maybe is that the cause of the problem.
